// Transcripción de la hoja de inventario físico de AGOSTO (escaneada).
// Formato: 'Nombre': [bulto, unidad, observación]. '' = casilla vacía.
module.exports = {
  'Aceite Vatel Pro': ['38', '', ''],
  'Aceite Portumesa': ['12', '', 'Cada caja trae 12 und'],
  'Aceite humo sésamo 5L': ['2', '', 'La caja trae 4 und'],
  'Arroz Mary': ['70', '', ''],
  'Azúcar dulcería blanca': ['', '26,95', 'El bulto trae 15 kg'],
  'Caraotas rojas Mary 500g': ['', '7', ''],
  'Harina de trigo': ['', '1', ''],
  'Harina Pan': ['1', '3', 'Harina Pan de 2 kg'],
  'Leche': ['', '1', ''],
  'Lentejas Mary 500g': ['', '9', ''],
  'Lentejas Pantera 500g': ['', '5', ''],
  'Arvejas Mary 400gr': ['', '16', ''],
  'Arvejas Pantera 900g': ['', '1', ''],
  'Mostaza': ['5', '3', ''],
  'Pasta corta': ['', '5', ''],
  'Pasta de tomate': ['', '3', ''],
  'Sal Cruz de Oro': ['5', '', ''],
  'Salsa agridulce sobre': ['4', '', ''],
  'Salsa agridulce racionada': ['', '30', ''],
  'Salsa soya sobre Usine': ['2', '', ''],
  'Salsa de soya negra concentrado': ['4', '2', 'La caja trae 4 und'],
  'Salsa soya clara (caja de 4)': ['1', '2', 'La caja trae 4 und'],
  'Salsa de soya negra El Chino Mushroom': ['1', '3', ''],
  'Salsa de la casa racionada': ['', '60', ''],
  'Salsa ketchup Tiquere caja 24': ['1', '9', ''],
  'Salsa de tomate Mayo 3,8kg': ['6', '', 'Cada bulto trae 4 und'],
  'Salsa de tomate Don Antonio': ['', '13', ''],
  'Salsa pote agridulce': ['', '13,25', '120 und'],
  'Salsa BBQ': ['3', '', 'Trae 24 und'],
  'Vinagre Sansone': ['4', '1', 'La caja trae 4 und'],

  'CT1 envases': ['4', '', '88 und'],
  'CT2 envases': ['9', '', '105 und'],
  'CT3 envases': ['8', '', '90 und'],
  'Tapa de tina de ensalada': ['8', '92', ''],
  'Tapas de tina china': ['5', '', ''],
  'Tina china 23oz': ['4', '', ''],
  'Tina de ensalada 6oz': ['6', '', ''],
  'Tina salsera 1oz Occidente': ['8', '', 'La caja trae 1000 und'],
  'Platos N10': ['25', '', '750 und'],
  'Platos N9': ['17', '90', ''],
  'Tenedores': ['22', '', ''],
  'Cuchillos': ['', '500', ''],
  'Vasos V67': ['2', '8', 'Paquetes · cada caja trae 25 paq'],
  'Pitillos': ['1', '', ''],
  'Bandejas térmicas para lumpias BT1': ['4', '', ''],
  'Bolsas de 2 kilos': ['32', '', ''],
  'Bolsas de 10 kilos': ['5', '', ''],
  'Bolsas de 15 kilos': ['13', '', ''],
  'Bolsas de 25 kilos': ['14', '', ''],
  'Bolsas de 40 kilos negra': ['6', '1', '1 paquete suelto'],
  'Bolsas transparentes 1/4': ['8', '', ''],

  'Agua Minalba 1,5L': ['3', '75', ''],
  'Agua Minalba 600ml': ['8', '19', ''],
  'Agua Glacier 550ml': ['4', '20', ''],
  'Gatorade de mandarina': ['2', '10', ''],
  'Gatorade de tropical': ['1', '', ''],
  'Jugo naranja 400ml Barinas': ['', '5', ''],
  'Jugo pera 400ml Barinas': ['', '5', ''],
  'Jugo manzana 400ml Barinas': ['', '8', ''],
  'Malta botella': ['2', '31', ''],
  'Refresco Manzanita 1L': ['', '7', ''],
  'Refresco Piña 1L': ['11', '12', ''],
  'Refresco Coca-Cola 1L': ['57', '', ''],
  'Refresco Colita 1L': ['3', '2', ''],
  'Refresco Fanta Naranja 1L': ['25', '10', ''],
  'Refresco Uva 1L': ['13', '', ''],
  'Refresco Toronja 2L': ['6', '', ''],
  'Refresco Manzanita 2L': ['6', '2', ''],
  'Refresco 7UP 2L': ['6', '1', ''],
  'Refresco Pepsi 2L': ['4', '', ''],
  'Refresco Coca-Cola 2L': ['5', '2', ''],
  'Refresco Colita 2L': ['6', '', ''],
  'Refresco Chinoto 2L': ['6', '', ''],
  'Refresco Naranja 2L': ['6', '', ''],
  'Té Lipton durazno': ['', '5', ''],
  'Té verde Lipton': ['', '10', ''],
  'Tenta té durazno 1L': ['43', '', ''],
  'Tenta té limón 1L': ['37', '', ''],
  'Tenta té durazno 500ml': ['', '1', ''],
  'Yukki pack pera': ['2', '13', ''],
  'Yukki pack manzana': ['', '23', ''],
  'Yukki pack durazno': ['', '23', ''],

  'Ají dulce': ['', '1,15', ''],
  'Ajinomoto': ['', '40,5', 'El bulto trae 25 kg'],
  'Ajo': ['', '3,5', ''],
  'Berenjena': ['', '1', ''],
  'Brócoli': ['', '0,55', ''],
  'Cebolla blanca': ['', '4,7', '3 + 1,70'],
  'Cebollín en cestas': ['', '23,75', ''],
  'Cebollín picado': ['', '30,7', ''],
  'Celeri (apio España)': ['', '0,35', ''],
  'Cilantro': ['', '0,3', ''],
  'Ensalada': ['', '90', ''],
  'Guayaba': ['', '4,3', ''],
  'Lechuga': ['', '1,25', ''],
  'Limón': ['', '5,5', ''],
  'Melón': ['', '4,05', ''],
  'Naranja': ['', '4,95', '3,25 + 1,70'],
  'Papas cestas': ['', '387,72', '21,51 × 18 cestas'],
  'Papelón': ['', '10', ''],
  'Parchita': ['', '3,55', ''],
  'Patilla': ['', '10', ''],
  'Pepino': ['', '0,9', ''],
  'Pimentón': ['', '3,7', ''],
  'Piña': ['', '2,8', ''],
  'Plátanos': ['', '8,55', '6 + 2,55'],
  'Queso': ['', '7,7', ''],
  'Remolacha': ['', '1,15', ''],
  'Repollo blanco': ['', '145,7', ''],
  'Repollo morado': ['', '12,75', ''],
  'Tomate': ['', '5,6', '3,65 + 1,95'],
  'Tomate de árbol': ['', '2', ''],
  'Vainita': ['', '0,5', ''],
  'Yuca': ['', '0,9', ''],
  'Zanahoria': ['', '9,65', ''],

  'Atún': ['', '1', ''],
  'Camarón': ['', '133,7', '23,70 + 110'],
  'Carne mechada': ['', '4,75', ''],
  'Carne molida': ['', '4,85', ''],
  'Carne bistec': ['', '4,85', ''],
  'Carne para guisar': ['', '4,85', ''],
  'Chuletas': ['', '6,7', ''],
  'Lagarto sin hueso': ['', '4,9', ''],
  'Empanizado para pollo': ['2', '', ''],
  'Empanizado para tender': ['6', '', ''],
  'Huevos': ['', '7', ''],   // confirmado por Alberto el 2/9: son 7 huevos sueltos
  'Magia': ['', '20,1', ''],
  'Marinado': ['6', '', ''],
  'Milanesa cocida': ['', '48,65', ''],
  'Milanesa congelada': ['', '82,25', ''],
  'Pollo en cestas marinado': ['17', '541,79', 'Recontado: 17 cestas. El peso sale del promedio de 31,87 kg por cesta'],
  'Polvo colorante 12U Brig-Red': ['', '26', ''],
  'Polvo colorante 12U Orangel Yelow': ['', '17', ''],
  'Polvo colorante amarillo Frutalia 500g': ['', '5', ''],
  'Tenders': ['', '36', 'Peso 5,90 kg'],

  'Citronela concentrado (amarillo)': ['', '2', ''],
  'Citronela preparado': ['', '8', ''],
  'Cloro concentrado': ['', '4', ''],
  'Cloro preparado': ['', '12', ''],
  'Coleto': ['', '16', '4 + 12'],
  'Desengrasante': ['', '20', ''],
  'Desinfectante concentrado azul': ['', '3', ''],
  'Desinfectante preparado azul': ['', '10', ''],
  'Desinfectante anaranjado concentrado': ['', '1,5', ''],
  'Desinfectante anaranjado preparado': ['', '10', ''],
  'Esponjas de brillo': ['3', '5', ''],
  'Esponja amarilla': ['', '20', ''],
  'Esponja de mayas': ['1', '', ''],
  'Jabón líquido': ['', '23', ''],
  'Pañitos': ['', '34', ''],
  'Trapeador limpia vidrios': ['', '1', ''],

  'Gorros tela sencilla': ['190', '', ''],
  'Guantes L y M': ['2', '1', ''],

  'Ligas': ['', '3', ''],
  'Panel LED redondo 6" 15W': ['', '1', ''],
  'Panel LED redondo 5" 9W': ['', '1', ''],
  'Resma de hojas blancas': ['', '3', ''],
  'Rollos térmicos impresora fiscal': ['2', '8', 'Paquetes'],
  'Rollos térmicos punto de venta': ['1', '', ''],
  'Teipe': ['', '2', ''],
  'Tinta para impresora negra': ['', '0,9', ''],

  'Papel antigrasa': ['1', '200', ''],
  'Papel antigrasa blanco lumpias': ['', '300', ''],
  'Papel higiénico bambú': ['3', '', ''],
  'Servilletas sin marca': ['8', '', ''],
  'Stikers': ['', '20', ''],
  'Filtro': ['7', '', ''],
  'Toallín': ['5', '', ''],
  'Papel Alison': ['2', '', ''],

  'Lumpias': ['', '100', ''],
  'Postres Paolo': ['', '7', ''],
  'Postres tres leches': ['', '8', ''],
  'Pinzas': ['', '5', '']
};
